[package]
name = "credentials_example"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
publish = false
autobins = false
description = """
An example of issuing, holding, and verifying a credential
"""

[[bin]]
name = "alice"
path = "src/bin/alice.rs"

[[bin]]
name = "bob"
path = "src/bin/bob.rs"

[dependencies]
ockam = { path = "../../../ockam" }
ockam_github = { path = "../../../ockam_github" }
